# Generated by Django 2.1.5 on 2019-02-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Client',
        ),
    ]
